### ISSUE TITLE
typing `.children`

### ISSUE THREAD

**Issue by jasongrout** [phosphorjs/phosphor-widget#16]
Is it easy to make the `.children` list more specifically typed? For example, with notebooks, I assume that everything in `.children` is a `CellWidget`. Can I express that nicely?

**Comment by sccolbert** [comment]
No, the current design does not allow for that. Most widgets which layout other widgets are designed to be flexible and layout *any* type of widget, so `Widget` is the common base. Your case is rare in that the container only supports *specific* types of children.
