### ISSUE TITLE
Discussion: Proposed API for 1.0

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphor-widget#4]
Pinging @blink1073, @dwillmer, @ellisonbg, @sylvaincorlay, @jasongrout

Please take a look at the current [API](https://github.com/phosphorjs/phosphor-widget/blob/master/src/index.ts) for Widget, and tell me what you think. I think it covers all the things we need in a base class. I'd like to call it stable and push out a 1.0 version this week. If you have any last minute suggestions or wishes, now is the time to speak up. Thanks!

Feel free to ping others who may care.

**Comment by ellisonbg** [comment]
Chris, thanks for pinging us. This looks really great!

On Sun, Aug 30, 2015 at 4:26 PM, S. Chris Colbert <notifications@github.com>
wrote:

> Pinging @blink1073 <https://github.com/blink1073>, @dwillmer
> <https://github.com/dwillmer>, @ellisonbg <https://github.com/ellisonbg>,
> @sylvaincorlay <https://github.com/sylvaincorlay>, @jasongrout
> <https://github.com/jasongrout>
>
> Please take a look at the current API
> <https://github.com/phosphorjs/phosphor-widget/blob/master/src/index.ts>
> for Widget, and tell me what you think. I think it covers all the things we
> need in a base class. I'd like to call it stable and push out a 1.0 version
> this week. If you have any last minute suggestions or wishes, now is the
> time to speak up. Thanks!
>
> Feel free to ping others who may care.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phosphorjs/phosphor-widget/issues/4>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
